# Generated by Django 5.2.9 on 2025-12-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
